### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by mmahut** [kovetskiy/zabbixctl#21]
Hello, do you plan to make a stable release at some point? Thank you.

**Comment by kovetskiy** [comment]
Hi. 

The program works stable for the last 3 years. I'm not a fan of point releases if you mean a fixed version, I think the program should be working at any commit after initial release, so active developments go in forks or separated branches and master contains _stable_ changes.

There is no active development since I don't use Zabbix anymore, but I am still passionate about open source projects and I'd be glad to accept any kinds of contributions.

**Comment by mmahut** [comment]
It would help a lot maintaining distributions to distinguish between versions.
